# -*- coding: utf-8 -*-
"""Pair_Trading (AAPL vs Microsoft).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ksRg9EVbNey3K-aOAi8f4DA-7DFY1el
"""

import yfinance as yf
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt


# =====================================================
# CONFIGURATION
# =====================================================
START_DATE = "2025-01-01"
END_DATE   = "2025-07-01"
STOCK1     = "AAPL"
STOCK2     = "MSFT"

EMA_SPAN = 5
STOP_LOSS_PCT = 0.0842
NO_TRADE_THRESHOLD = 0.1
UPPER_Q = 0.85
LOWER_Q = 0.15


# =====================================================
# DATA DOWNLOAD
# =====================================================
def download_data(stock1, stock2, start, end):

    df1 = yf.download(stock1, start=start, end=end)['Close']
    df2 = yf.download(stock2, start=start, end=end)['Close']

    data = pd.concat([df1, df2], axis=1, join='inner').dropna()
    data.columns = ['asset1_close', 'asset2_close']

    return data


# =====================================================
# STRATEGY ENGINE
# =====================================================
def pairs_trading_strategy(data):

    # ---------- 1. Hedge Ratio via OLS ----------
    X = sm.add_constant(data['asset2_close'])
    model = sm.OLS(data['asset1_close'], X).fit()
    hedge_ratio = model.params['asset2_close']

    # ---------- 2. Spread & Z-score ----------
    spread = data['asset1_close'] - hedge_ratio * data['asset2_close']
    z_score = (spread - spread.mean()) / spread.std()

    ema_spread = spread.ewm(span=EMA_SPAN, adjust=False).mean()
    ema_z = z_score.ewm(span=EMA_SPAN, adjust=False).mean()

    upper_threshold_z = z_score.quantile(UPPER_Q)
    lower_threshold_z = z_score.quantile(LOWER_Q)

    # ---------- 3. Threshold & EMA Cross Logic ----------
    threshold_cross_above = (z_score.shift(1) <= upper_threshold_z) & (z_score > upper_threshold_z)
    threshold_cross_below = (z_score.shift(1) >= lower_threshold_z) & (z_score < lower_threshold_z)

    ema_cross_above = (z_score.shift(1) <= ema_z.shift(1)) & (z_score > ema_z)
    ema_cross_below = (z_score.shift(1) >= ema_z.shift(1)) & (z_score < ema_z)

    # ---------- 4. Initialize State ----------
    position = 0
    entry_spread = None
    waiting_for_short = False
    waiting_for_long = False

    short_signal = []
    long_signal = []
    exit_signal = []
    stop_signal = []
    position_list = []

    # ---------- 5. Trading Loop ----------
    for i in range(len(data)):

        if i == 0:
            short_signal.append(0)
            long_signal.append(0)
            exit_signal.append(0)
            stop_signal.append(0)
            position_list.append(0)
            continue

        # Detect threshold break events
        if threshold_cross_above.iloc[i]:
            waiting_for_short = True
        elif threshold_cross_below.iloc[i]:
            waiting_for_long = True

        short_s = long_s = exit_s = stop_s = 0

        # ================= ENTRY LOGIC =================
        if position == 0:

            # SHORT ENTRY
            if (waiting_for_short and
                ema_cross_below.iloc[i] and
                z_score.iloc[i] > upper_threshold_z):

                position = -1
                entry_spread = spread.iloc[i]
                short_s = 1
                waiting_for_short = False

            # LONG ENTRY
            elif (waiting_for_long and
                  ema_cross_above.iloc[i] and
                  z_score.iloc[i] < lower_threshold_z):

                position = 1
                entry_spread = spread.iloc[i]
                long_s = 1
                waiting_for_long = False

        # ================= EXIT LOGIC =================
        else:

            # ---- Stop Loss First ----
            if position == 1:
                stop_level = entry_spread * (1 - STOP_LOSS_PCT)
                if spread.iloc[i] < stop_level:
                    position = 0
                    stop_s = 1
                    entry_spread = None

            elif position == -1:
                stop_level = entry_spread * (1 + STOP_LOSS_PCT)
                if spread.iloc[i] > stop_level:
                    position = 0
                    stop_s = 1
                    entry_spread = None

            # ---- Regular Exit Near Mean ----
            if position != 0 and abs(z_score.iloc[i]) <= NO_TRADE_THRESHOLD:
                position = 0
                exit_s = 1
                entry_spread = None

        short_signal.append(short_s)
        long_signal.append(long_s)
        exit_signal.append(exit_s)
        stop_signal.append(stop_s)
        position_list.append(position)

    # ---------- 6. Compile Results ----------
    result = data.copy()
    result['Hedge Ratio'] = hedge_ratio
    result['Spread'] = spread
    result['Z Score'] = z_score
    result['EMA Spread'] = ema_spread
    result['EMA Z Score'] = ema_z
    result['Short Signal'] = short_signal
    result['Long Signal'] = long_signal
    result['Exit Signal'] = exit_signal
    result['Stop Loss Signal'] = stop_signal
    result['Position'] = position_list

    return result


# =====================================================
# FULL VISUALIZATION (WITH ALL LEGENDS & MARKERS)
# =====================================================
def plot_results(result):

    upper_z = result['Z Score'].quantile(UPPER_Q)
    lower_z = result['Z Score'].quantile(LOWER_Q)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 11), sharex=True)

    # ================= SPREAD PLOT =================
    ax1.plot(result.index, result['Spread'], label='Spread', color='dodgerblue')
    ax1.plot(result.index, result['EMA Spread'], label='EMA Spread', color='orange')

    ax1.axhline(result['Spread'].mean(), color='red', linestyle='--', label='Mean')
    ax1.axhline(result['Spread'].quantile(UPPER_Q), color='green', linestyle='--', label='Upper Threshold (85th)')
    ax1.axhline(result['Spread'].quantile(LOWER_Q), color='purple', linestyle='--', label='Lower Threshold (15th)')

    ax1.set_title("Spread & EMA")
    ax1.set_ylabel("Spread")
    ax1.legend()
    ax1.grid(True)

    # ================= Z SCORE PLOT =================
    ax2.plot(result.index, result['Z Score'], label='Z Score', color='blue')
    ax2.plot(result.index, result['EMA Z Score'], label='EMA Z Score', color='orange')

    ax2.axhline(0, color='red', linestyle='--', label='Mean (0)')
    ax2.axhline(upper_z, color='green', linestyle='--', label='Upper Threshold (85th)')
    ax2.axhline(lower_z, color='purple', linestyle='--', label='Lower Threshold (15th)')
    ax2.axhline(NO_TRADE_THRESHOLD, color='gray', linestyle=':', label='No-Trade Zone')
    ax2.axhline(-NO_TRADE_THRESHOLD, color='gray', linestyle=':')

    # ---- Signals ----
    short_points = result[result['Short Signal'] == 1]['Z Score']
    ax2.scatter(short_points.index, short_points, marker='v', color='red', label='Short Entry', zorder=5)

    long_points = result[result['Long Signal'] == 1]['Z Score']
    ax2.scatter(long_points.index, long_points, marker='^', color='lime', label='Long Entry', zorder=5)

    exit_points = result[result['Exit Signal'] == 1]['Z Score']
    ax2.scatter(exit_points.index, exit_points, marker='x', color='black', label='Exit', zorder=5)

    stop_points = result[result['Stop Loss Signal'] == 1]['Z Score']
    ax2.scatter(stop_points.index, stop_points, marker='o', color='purple', label='Stop Loss', zorder=5)

    ax2.set_title("Z Score, EMA & Trading Signals")
    ax2.set_xlabel("Time")
    ax2.set_ylabel("Z Score")
    ax2.legend()
    ax2.grid(True)

    plt.tight_layout()
    plt.show()


# =====================================================
# RUN SCRIPT
# =====================================================
if __name__ == "__main__":

    data = download_data(STOCK1, STOCK2, START_DATE, END_DATE)

    result = pairs_trading_strategy(data)

    result.to_excel("Backtest_Results_AAPL_MSFT.xlsx")
    print("Backtest complete. Results saved.")

    plot_results(result)

# BACKTEST ENGINE

def backtest(df, trade_size=10000):

    df = df.copy()

    # ---------------------------------------------
    # Initialize Performance Columns
    # ---------------------------------------------
    df["PnL"] = 0.0
    df["Cumulative PnL"] = 0.0

    hedge_ratio = df["Hedge Ratio"].iloc[0]

    position = 0
    entry_price1 = None
    entry_price2 = None
    quantity1 = 0
    quantity2 = 0

    trade_log = []
    total_trades = 0
    winning_trades = 0
    winning_returns = []

    # ---------------------------------------------
    # Main Backtest Loop
    # ---------------------------------------------
    for i in range(1, len(df)):

        date = df.index[i]
        price1 = df["asset1_close"].iloc[i]
        price2 = df["asset2_close"].iloc[i]

        long_signal  = df["Long Signal"].iloc[i]
        short_signal = df["Short Signal"].iloc[i]
        exit_signal  = df["Exit Signal"].iloc[i]
        stop_signal  = df["Stop Loss Signal"].iloc[i]

        # ================= ENTRY =================
        if position == 0:

            if long_signal:
                position = 1
                total_trades += 1

                entry_price1 = price1
                entry_price2 = price2

                quantity1 = trade_size / price1
                quantity2 = (trade_size * hedge_ratio) / price2

                trade_log.append(("ENTRY LONG", date, price1, price2))

            elif short_signal:
                position = -1
                total_trades += 1

                entry_price1 = price1
                entry_price2 = price2

                quantity1 = trade_size / price1
                quantity2 = (trade_size * hedge_ratio) / price2

                trade_log.append(("ENTRY SHORT", date, price1, price2))

        # ================= LONG EXIT =================
        elif position == 1 and (exit_signal or stop_signal):

            pnl = (
                (price1 - entry_price1) * quantity1 +
                (entry_price2 - price2) * quantity2
            )

            df.at[date, "PnL"] = pnl

            trade_return = pnl / trade_size

            if pnl > 0:
                winning_trades += 1
                winning_returns.append(trade_return)

            exit_type = "STOP LOSS LONG" if stop_signal else "EXIT LONG"
            trade_log.append((exit_type, date, pnl, trade_return))

            position = 0

        # ================= SHORT EXIT =================
        elif position == -1 and (exit_signal or stop_signal):

            pnl = (
                (entry_price1 - price1) * quantity1 +
                (price2 - entry_price2) * quantity2
            )

            df.at[date, "PnL"] = pnl

            trade_return = pnl / trade_size

            if pnl > 0:
                winning_trades += 1
                winning_returns.append(trade_return)

            exit_type = "STOP LOSS SHORT" if stop_signal else "EXIT SHORT"
            trade_log.append((exit_type, date, pnl, trade_return))

            position = 0

        df.at[date, "Position"] = position

    # ---------------------------------------------
    # Performance Metrics
    # ---------------------------------------------
    df["Cumulative PnL"] = df["PnL"].cumsum()

    final_pnl = df["Cumulative PnL"].iloc[-1]
    win_rate = (winning_trades / total_trades * 100) if total_trades > 0 else 0
    avg_return = (
        sum(winning_returns) / winning_trades * 100
        if winning_trades > 0 else 0
    )

    # ---------------------------------------------
    # Summary Output
    # ---------------------------------------------
    print("\n================ BACKTEST SUMMARY ================")
    print(f"Final P&L: ${final_pnl:,.2f}")
    print(f"Total Trades: {total_trades}")
    print(f"Winning Trades: {winning_trades}")
    print(f"Win Rate: {win_rate:.2f}%")
    print(f"Average Winning Return: {avg_return:.2f}%")

    print("\n================ TRADE LOG =======================")
    for trade in trade_log:
        print(trade)

    return df

# =====================================================
# RUN FULL PIPELINE
# =====================================================
if __name__ == "__main__":

    # 1️⃣ Download Data
    data = download_data(STOCK1, STOCK2, START_DATE, END_DATE)

    # 2️⃣ Generate Strategy Signals
    result = pairs_trading_strategy(data)

    # 3️⃣ Run Backtest
    backtest_result = backtest(result, trade_size=10000)

    # 4️⃣ Save Results
    backtest_result.to_excel("Backtest_Results_AAPL_MSFT.xlsx")
    print("\nResults saved to Excel.")

    # 5️⃣ Plot Signals
    plot_results(backtest_result)

